CREATE TABLE IF NOT EXISTS crawl_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    url TEXT NOT NULL,
    ok INTEGER NOT NULL,
    status TEXT,
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
